language: generic

sudo: false

addons:
  apt:
    sources:
    - cassou-emacs

env:
  - EVM_EMACS=emacs-27.1-travis-linux-xenial

before_install:
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - git clone https://github.com/cask/cask.git "$HOME/.cask"
  - export PATH="$HOME/.cask/bin:$PATH"

install:
  - cask install

script:
  - cask exec ert-runner
  - cask exec emacs -Q -batch -L . -eval "(require 'org-babel-eval-in-repl) (batch-byte-compile)" *.el
  - cask exec ert-runner
  - cask clean-elc

# Local Variables:
# coding: utf-8
# End:
